In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
data = pd.read_csv("../features/base_colombia_completa.csv", sep=";")

In [9]:
data

,Municipality code,Municipality,Date,temperature,month_str,month,year,concat_code_year_month,precipitation,cases,...,Householdswithoutwateraccess(%),Householdswithoutinternetaccess(%),Buildingstratification1(%),Buildingstratification2(%),Buildingstratification3(%),Buildingstratification4(%),Buildingstratification5(%),Buildingstratification6(%),NumberofhospitalsperKm2,NumberofhousesperKm2
0,5001,Medellín,TEMPERATURE_jan_07,21.009283,jan,1,2007,5001|2007|1,65.411400,1,...,1.44,29.47,12.1117,31.2817,26.0471,9.0279,6.4855,3.7062,1.555263,2102.057895
1,5002,Abejorral,TEMPERATURE_jan_07,16.566818,jan,1,2007,5002|2007|1,73.411079,0,...,21.87,56.27,31.3520,33.8306,2.0439,0.0352,0.0117,0.0000,0.002012,11.945674
2,5004,Abriaquí,TEMPERATURE_jan_07,16.988332,jan,1,2007,5004|2007|1,53.842678,0,...,24.03,62.35,21.5705,39.1675,4.3519,0.0946,0.1892,0.1892,0.000000,2.548276
3,5021,Alejandría,TEMPERATURE_jan_07,20.606707,jan,1,2007,5021|2007|1,66.638855,0,...,17.06,54.61,17.9879,38.5721,4.8215,0.1854,0.0464,0.0464,0.006623,9.092715
4,5030,Amagá,TEMPERATURE_jan_07,20.814870,jan,1,2007,5030|2007|1,62.527489,0,...,3.31,56.12,27.8784,42.0280,3.4086,0.1889,0.1460,0.0172,0.011765,102.752941
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161419,97889,Yavaraté,TEMPERATURE_dec_18,26.300149,dec,12,2018,97889|2018|12,278.270264,0,...,92.93,75.76,6.0606,1.0101,0.0000,0.0000,0.0000,0.0000,0.000000,0.028621
161420,99001,Puerto Carreño,TEMPERATURE_dec_18,28.290137,dec,12,2018,99001|2018|12,46.351234,0,...,32.52,68.68,41.0368,15.3779,2.4037,0.0579,0.0145,0.0145,0.000388,0.432426
161421,99524,La Primavera,TEMPERATURE_dec_18,28.010822,dec,12,2018,99524|2018|12,56.324593,0,...,26.46,72.64,39.3295,5.0284,0.7782,0.0299,0.0000,0.0000,0.000000,0.113272
161422,99624,Santa Rosalía,TEMPERATURE_dec_18,27.512444,dec,12,2018,99624|2018|12,55.008774,0,...,27.58,81.35,50.2627,7.0053,0.2627,0.0000,0.0000,0.0000,0.000254,0.247904
161423,99773,Cumaribo,TEMPERATURE_dec_18,27.309817,dec,12,2018,99773|2018|12,82.457962,0,...,81.47,86.83,10.5047,0.4311,0.1998,0.0000,0.0000,0.0000,0.000061,0.134017

In [10]:
data.columns

Index(['Municipality code', 'Municipality', 'Date', 'temperature', 'month_str',
       'month', 'year', 'concat_code_year_month', 'precipitation', 'cases',
       'concat_code_year', 'population', 'year_cases', 'tasa_dengue_mensual',
       'tasa_dengue_mensual_x10000_habitantes', 'Age0-4(%)', 'Age5-14(%)',
       'Age15-29(%)', 'Age>30(%)', 'AfrocolombianPopulation(%)',
       'IndianPopulation(%)', 'PeoplewithDisabilities(%)',
       'Peoplewhocannotreadorwrite(%)', 'Secondary/HigherEducation(%)',
       'Employedpopulation(%)', 'Unemployedpopulation(%)',
       'Peopledoinghousework(%)', 'Retiredpeople(%)', 'Men(%)', 'Women(%)',
       'Householdswithoutwateraccess(%)', 'Householdswithoutinternetaccess(%)',
       'Buildingstratification1(%)', 'Buildingstratification2(%)',
       'Buildingstratification3(%)', 'Buildingstratification4(%)',
       'Buildingstratification5(%)', 'Buildingstratification6(%)',
       'NumberofhospitalsperKm2', 'NumberofhousesperKm2'],
      dtype='object')

In [28]:
tasas_promedio_df = data.groupby(['Municipality code'])[['tasa_dengue_mensual', 'tasa_dengue_mensual_x10000_habitantes']].mean().reset_index()

In [29]:
tasas_promedio_df.rename(columns={'tasa_dengue_mensual':'promedio_tasa_dengue_mensual', 
                                 'tasa_dengue_mensual_x10000_habitantes':'promedio_tasa_dengue_mensual_x10000_habitantes'},
                        inplace=True)
tasas_promedio_df

,Municipality code,promedio_tasa_dengue_mensual,promedio_tasa_dengue_mensual_x10000_habitantes
0,5001,0.000140,1.398562
1,5002,0.000030,0.298171
2,5004,0.000017,0.169010
3,5021,0.000018,0.175392
4,5030,0.000158,1.582632
...,...,...,...
1116,97889,0.000011,0.111717
1117,99001,0.000368,3.677812
1118,99524,0.000251,2.512306
1119,99624,0.000382,3.818935
1120,99773,0.000097,0.965451

In [30]:
tasas_promedio_df.to_csv("tasas_dengue_promedio.csv", sep=";", index=False)

In [32]:
data_complete = data.merge(tasas_promedio_df, on='Municipality code', how='left')
data_complete

,Municipality code,Municipality,Date,temperature,month_str,month,year,concat_code_year_month,precipitation,cases,...,Buildingstratification1(%),Buildingstratification2(%),Buildingstratification3(%),Buildingstratification4(%),Buildingstratification5(%),Buildingstratification6(%),NumberofhospitalsperKm2,NumberofhousesperKm2,promedio_tasa_dengue_mensual,promedio_tasa_dengue_mensual_x10000_habitantes
0,5001,Medellín,TEMPERATURE_jan_07,21.009283,jan,1,2007,5001|2007|1,65.411400,1,...,12.1117,31.2817,26.0471,9.0279,6.4855,3.7062,1.555263,2102.057895,0.000140,1.398562
1,5002,Abejorral,TEMPERATURE_jan_07,16.566818,jan,1,2007,5002|2007|1,73.411079,0,...,31.3520,33.8306,2.0439,0.0352,0.0117,0.0000,0.002012,11.945674,0.000030,0.298171
2,5004,Abriaquí,TEMPERATURE_jan_07,16.988332,jan,1,2007,5004|2007|1,53.842678,0,...,21.5705,39.1675,4.3519,0.0946,0.1892,0.1892,0.000000,2.548276,0.000017,0.169010
3,5021,Alejandría,TEMPERATURE_jan_07,20.606707,jan,1,2007,5021|2007|1,66.638855,0,...,17.9879,38.5721,4.8215,0.1854,0.0464,0.0464,0.006623,9.092715,0.000018,0.175392
4,5030,Amagá,TEMPERATURE_jan_07,20.814870,jan,1,2007,5030|2007|1,62.527489,0,...,27.8784,42.0280,3.4086,0.1889,0.1460,0.0172,0.011765,102.752941,0.000158,1.582632
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161419,97889,Yavaraté,TEMPERATURE_dec_18,26.300149,dec,12,2018,97889|2018|12,278.270264,0,...,6.0606,1.0101,0.0000,0.0000,0.0000,0.0000,0.000000,0.028621,0.000011,0.111717
161420,99001,Puerto Carreño,TEMPERATURE_dec_18,28.290137,dec,12,2018,99001|2018|12,46.351234,0,...,41.0368,15.3779,2.4037,0.0579,0.0145,0.0145,0.000388,0.432426,0.000368,3.677812
161421,99524,La Primavera,TEMPERATURE_dec_18,28.010822,dec,12,2018,99524|2018|12,56.324593,0,...,39.3295,5.0284,0.7782,0.0299,0.0000,0.0000,0.000000,0.113272,0.000251,2.512306
161422,99624,Santa Rosalía,TEMPERATURE_dec_18,27.512444,dec,12,2018,99624|2018|12,55.008774,0,...,50.2627,7.0053,0.2627,0.0000,0.0000,0.0000,0.000254,0.247904,0.000382,3.818935
161423,99773,Cumaribo,TEMPERATURE_dec_18,27.309817,dec,12,2018,99773|2018|12,82.457962,0,...,10.5047,0.4311,0.1998,0.0000,0.0000,0.0000,0.000061,0.134017,0.000097,0.965451

In [33]:
data_complete.to_csv("../features/data_colombia_completa_2.csv", sep=";", index=False)